### ISSUE TITLE
在Aop中获取注册的dbkey

### ISSUE THREAD

**Issue by MJTucDi** [2881099/FreeSql.Cloud#3]
叶老板好 我想在Aop中获取 注册的dbkey
![image](https://user-images.githubusercontent.com/7964859/189042711-9ff5199d-c0e5-4f9c-83ba-4d22a3e31f57.png)

**Comment by 2881099** [comment]
aop 要分别在 Register 委托内设置

**Comment by 2881099** [comment]
fsql.Register(dbkey, () =>
{
var ret = new FreeSqlBuilder()
...;
//aop
return ret;
});

**Comment by MJTucDi** [comment]
get[抱拳]
