### ISSUE TITLE
数据库连接释放问题

### ISSUE THREAD

**Issue by Tangtang1997** [2881099/FreeSql.Cloud#8]
大佬您好，请教一下，当短时间内Register的库过多，这些数据库连接都没有释放，到达一定数量时会导致MySQL提示 “Too many connections” 错误，当前已经达到了MySQL服务器允许的最大并发连接数

![1717494252214](https://github.com/2881099/FreeSql.Cloud/assets/46021085/b5b97e5f-7c14-453d-9579-069612baee9b)

这个问题让我挺矛盾的
- 可以通过修改MySQL配置文件增加最大连接数，或者限制分库的数量来解决 “Too many connections” 的问题，请问有没有办法每次使用完立即将连接释放掉？
- 如果可以每次用完立即释放掉连接，是不是违反了连接复用的初衷？

我尝试不使用FreeSqlCloud，使用IFreeSql对象，在crud操作的时候，往AsTable()函数中传入库名，
```csharp
await freeSql.Insert<Student>().AsTable("库名.表名").ExecuteAffrowsAsync();
```
这样也可以实现向目标库的增删改查，只是没有使用FreeSqlCloud操作方便

**Comment by 2881099** [comment]
如果是同一台服务器，只是不同数据库，直接用 AsTable 解决。

**Comment by Tangtang1997** [comment]
thank you!
